apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate-check
spec:
  metrics:
    - name: sample-job-check
      successCondition: result == "successful"
      failureCondition: result == "failed"
      provider:
        job:
          spec:
            backoffLimit: 1
            template:
              spec:
                restartPolicy: Never
                containers:
                  - name: test
                    image: busybox
                    command: ["/bin/sh", "-c"]
                    args: ["echo successful"]
